import type { Topic, GlossaryEntry } from '../../types/messages';
import type { AnchorBookmark } from '../../hooks/useLiveAnchor';

interface BuildMarkdownInput {
  meetingId: string;
  userName?: string;
  freeform: string;
  topics: Topic[];
  glossary: GlossaryEntry[];
  bookmarks: AnchorBookmark[];
  generatedAt?: number;
}

function formatDate(ms: number): string {
  return new Date(ms).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatClockTime(ms: number): string {
  const d = new Date(ms);
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
}

function formatClockTimeWithSeconds(ms: number): string {
  const d = new Date(ms);
  return `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}:${String(d.getSeconds()).padStart(2, '0')}`;
}

function shortMeetingId(id: string): string {
  if (!id) return 'unknown';
  return id.length > 12 ? `${id.slice(0, 8)}…` : id;
}

export function buildMarkdown(input: BuildMarkdownInput): string {
  const generatedAt = input.generatedAt ?? Date.now();
  const sections: string[] = [];

  sections.push('# Class Notes');
  const metaLines: string[] = [];
  metaLines.push(`**Date:** ${formatDate(generatedAt)}`);
  metaLines.push(`**Generated:** ${formatClockTime(generatedAt)}`);
  if (input.userName) metaLines.push(`**Student:** ${input.userName}`);
  metaLines.push(`**Meeting:** ${shortMeetingId(input.meetingId)}`);
  sections.push(metaLines.join('  \n'));

  sections.push('---');
  sections.push('## My Notes');
  const trimmedFreeform = input.freeform.trim();
  sections.push(trimmedFreeform.length > 0 ? trimmedFreeform : '_(empty)_');

  if (input.topics.length > 0) {
    sections.push('---');
    const topicsSorted = [...input.topics].sort((a, b) => a.startTime - b.startTime);
    const topicLines: string[] = [`## Topics Covered (${topicsSorted.length})`];
    topicsSorted.forEach(topic => {
      topicLines.push('');
      topicLines.push(`### ${topic.title}`);
      topicLines.push(`_Started ${formatClockTime(topic.startTime)}_`);
      if (topic.bullets.length > 0) {
        topicLines.push('');
        topic.bullets.forEach(bullet => topicLines.push(`- ${bullet}`));
      }
    });
    sections.push(topicLines.join('\n'));
  }

  if (input.glossary.length > 0) {
    sections.push('---');
    const glossarySorted = [...input.glossary].sort((a, b) => a.timestamp - b.timestamp);
    const glossaryLines: string[] = [`## Glossary & Formulas (${glossarySorted.length})`, ''];
    glossarySorted.forEach(entry => {
      glossaryLines.push(`**${entry.term}** — ${entry.definition}`);
      if (entry.formula) {
        glossaryLines.push('');
        glossaryLines.push('```');
        glossaryLines.push(entry.formula);
        glossaryLines.push('```');
      }
      glossaryLines.push('');
    });
    sections.push(glossaryLines.join('\n').trimEnd());
  }

  if (input.bookmarks.length > 0) {
    sections.push('---');
    const bookmarksSorted = [...input.bookmarks].sort((a, b) => a.timestamp - b.timestamp);
    const bookmarkLines: string[] = [`## Bookmarks (${bookmarksSorted.length})`, ''];
    bookmarksSorted.forEach(b => {
      const tag = b.isAuto ? '⭐ ' : '';
      const snippet = b.transcriptSnippet ? ` — _"${b.transcriptSnippet.replace(/_/g, '\\_')}"_` : '';
      bookmarkLines.push(`- **${formatClockTimeWithSeconds(b.timestamp)}** ${tag}${b.topic}${snippet}`);
    });
    sections.push(bookmarkLines.join('\n'));
  }

  sections.push('---');
  sections.push('_Generated by Zoom Momentum Smart Notes_');

  return sections.join('\n\n') + '\n';
}

export function buildFilename(meetingId: string, generatedAt: number = Date.now()): string {
  const d = new Date(generatedAt);
  const datePart = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  const idPart = (meetingId || 'unknown').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 8) || 'session';
  return `class-notes-${datePart}-${idPart}.md`;
}
